"""edges table

Revision ID: 23867006d7e3
Revises: 1ef8974d9b43
Create Date: 2020-09-28 19:07:35.534667

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23867006d7e3'
down_revision = '1ef8974d9b43'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('edge',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('u', sa.Integer(), nullable=True),
    sa.Column('v', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['u'], ['node.id'], ),
    sa.ForeignKeyConstraint(['v'], ['node.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('edge')
    # ### end Alembic commands ###
